### ISSUE TITLE
Unable to delete / move to trash

### ISSUE THREAD

**Issue by cnstt** [flathub/com.zettlr.Zettlr#8]
When wanting to delete a folder (move to trash), nothing happens. I get this error message in the command line:
`gio: file:///udd/username/Documents/Zettlr%20Tutorial/folder/folder: Trash portal failed on /udd/username/Documents/Zettlr Tutorial/folder/folder`

**Comment by Lunarequest** [comment]
I've added the correct dbus part required to the permission it should work now

**Comment by Lunarequest** [comment]
I'm

**Comment by cnstt** [comment]
I still get the same error somehow... might this be related to the following error I get? `[3:0628/150549.614809:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
`

**Comment by Lunarequest** [comment]
that is an unrelated error(completely ignore-able), I'll poke it at this more

**Comment by Lunarequest** [comment]
I've fixed the issue properly and verified it with various files.
